services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ~/Music/MyLib:/music
      - ~/Music/Input:/downloads
    ports:
      - "8337:8337"
    restart: unless-stopped
